### ISSUE TITLE
Enhacement request: JDK 8 support

### ISSUE THREAD

**Issue by dsimansk** [fabric8io/java-main#10]
Hi,
could you please considerer adding another branch and related tag to DockerHub to support JDK 8 also. `fabric8/base-sti` repo already has the branch, but automated build is not configured.

Thanks in advance.

**Comment by dsimansk** [comment]
Hi, @jimmidyson. I guess this issue is irrelevant and out dated due to work being done on https://github.com/fabric8io/base-images/, right?

**Comment by jimmidyson** [comment]
@dsimansk Yes it is - we should put a note in the README. Thanks for pointing it out.
