### ISSUE TITLE
[OSE3] run script fails because pods are run under random UID

### ISSUE THREAD

**Issue by dsimansk** [fabric8io/java-main#7]
Since the RC versions of OSE 3 and in GA, where security context is present and pods are run under random UID. The `run` script can't list and run *.jar anymore, fails with permissions denied on `ls`.

**Comment by jimmidyson** [comment]
@dsimansk Thanks for the report - we know about the problems & are working to resolve them.

**Comment by dsimansk** [comment]
@jimmidyson I've built my own image on top with `RUN chmod -R a+rwX /opt/jboss`, but that isn't very nice :)

**Comment by jimmidyson** [comment]
@dsimansk Agreed. With the java-main there should be no need for anything to be writeable in the container afaik. But everything should be readable at least. Any runtime data should be written to volumes which will be configured properly by OSE.

**Comment by jimmidyson** [comment]
@dsimansk Could you share the full output of the failure? Do you have an example project I can recreate it with?

**Comment by dsimansk** [comment]
@jimmidyson you should be able to reproduce it with https://github.com/dsimansk/amq-app, it should have AMQ running, but you should see the error anyway.

Build log end with success, but `run` produce this output

``` bash
# oc logs amq-app-deployment-1-9to60 -n dsimansk
/tmp/scripts/run: line 31: pushd: /opt/jboss/deploy: Permission denied
ls: cannot access *.jar: Permission denied
/tmp/scripts/run: line 33: popd: directory stack empty
ls: cannot access /opt/jboss/deploy/dependency/*.jar: Permission denied
I> No access restrictor found, access to all MBean is allowed
I> No suitable address found for listening on multicast discovery requests
Jolokia: Agent started with URL http://10.1.2.162:8778/jolokia/
Error: Could not find or load main class com.redhat.xpaas.amq.app.Main
```

I woudl say this part of deploymentConfig is problematic :)

``` json
          "securityContext": {
                    "capabilities": {},
                    "privileged": false,
                    "seLinuxOptions": {
                        "level": "s0:c12,c4"
                    },
                    "runAsUser": 1000140000
                }
```

**Comment by jimmidyson** [comment]
@dsimansk So the problem is that /opt/jboss dir has perms of 700 owned by jboss user. I'll see where the best place to change this is - it could be in the base image itself but I'll find out, fix it & let you know.

**Comment by dsimansk** [comment]
@jimmidyson fabric8/base-sti seem reasonable, I would go for it. One other thought, would you mind creating another version on top of jboss/base-jdk:8 to get JDK 8 supported also.

**Comment by jimmidyson** [comment]
@dsimansk Yeah sure! I think actually we're going to change it in jboss/base - PR submitted to https://github.com/jboss-dockerfiles/base/pull/3

**Comment by dsimansk** [comment]
Seems to be resolved after your PRs. Nice to see the final image loosen a bit of weight on the way (~500MB in total) ;)

Closing this issue as it was resolved in jboss/base.

**Comment by jimmidyson** [comment]
Awesome! Thanks for the feedback.
